language: node_js

script:
  - set -e
  - npm run lint
  - npm run test-headless
  - npm run build-ngx-cookie-consent
  - npm run build-web-component
  - cd dist/lacosanostra/ngx-cookie-consent

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      branch: master
  - provider: script
    script: ./.travis-commit-changes.sh
    on:
      branch: master