language: node_js

script:
  - set -e
  - npm run lint
  - npm run test-headless
  - npm run build-ngx-cookie-consent
  - npm run build-web-component

before_deploy:
  - cd dist/lacosanostra/ngx-cookie-consent
deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
  - provider: script
    skip_cleanup: true
    script: cd ../../../ && ./.travis-commit-changes.sh
